name: build and push docker image

on:
  push:
    branches:
      - "main"
      - "e2e-test"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/autodev:latest
          outputs: type=docker,dest=/tmp/autodev.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/autodev.tar
  e2e-test:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
      -
        name: check cluster nodes to verify readiness
        run: kubectl get nodes
      -
        name: install nginx ingress controller
        run: |
          kubectl apply -f \
            https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
      # -
      #   name: wait for nginx ingress controller to be ready
      #   run: |
      #     kubectl wait --namespace ingress-nginx \
      #       --for=condition=ready pod \
      #       --selector=app.kubernetes.io/component=controller \
      #       --timeout=90s
      -
        name: get ingress controller logs
        run: |
          sleep 10
          kubectl -n ingress-nginx get all
          kubectl logs -n ingress-nginx deployment/ingress-nginx-controller
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: create minimal-ingress
        run: kubectl apply -f ./k8s-manifests/minimal-ingress.yaml
      -
        name: get ingress
        run: kubectl get ingress
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: autodev
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/autodev.tar
          docker image ls -a

